# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eac6efcf20b1b452c52acf5a9967eae515fed1f51830df82f8830f910cffa2bc74d3d1441859b41e453b90708cb58fea9d1fdec464f4a48379bd0bfad71ea741

test:
  secret_key_base: 32135b3bef9cf1242ae5c37670f4e51fd6cc4c38b1ffedb77207aac3c03ded88326df255103671e95d1153d5010db5259d430ec0852c764fd1003b2c535f7ec6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
